services:
  db:
   image: postgres
   container_name: db
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
   volumes:
     - postgres:/var/lib/postgresql/data
   networks:
     - backend

  redis:
    image: redis
    container_name: redis
    networks:
      - backend

  vote:
    build: 
     context: ./vote
     dockerfile: Dockerfile
    command: python app.py
    container_name: vote
    ports:
      - "5000:80"
    networks:
      - frontend
      - backend
    volumes:
      - votes:/app

  worker:
    build: 
     context: ./worker
     dockerfile: Dockerfile
    container_name: worker
    networks:
      - backend
    volumes:
      - workers:/app

  result:
    build:
     context: ./result
     dockerfile: Dockerfile
    command: nodemon server.js
    container_name: result
    ports:
      - "5001:80"
    networks:
      - frontend
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true

volumes:
  postgres:
  votes:
  workers:
