name: Build and Test and Deploy
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout of the repo
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install Dependencies
        run: npm install
      - name: Run Integration Tests
        run: npm run test:unit

  user_interface_tests:
    runs-on: ubuntu-latest
    needs: integration_tests
    steps:
      - name: Checkout of the repo
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install Dependencies
        run: npm install
      - name: Install Playwright
        run: npx playwright install
      - name: Run User Interface Tests
        run: npm run test:ui
      - name: Chec–∫ SoftUni username - jvalkov
        run: echo "SoftUni Username - jvalkov"

  deploy_to_render:
    runs-on: ubuntu-latest
    needs: user_interface_tests
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout of the repo
        uses: actions/checkout@v4
      - name: Deploy to Render in Production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_WEB_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
