--CREATE DATABASE SoftUni
--USE SoftUni

CREATE TABLE Towns
(
Id INT PRIMARY KEY IDENTITY(1,1),
[Name] VARCHAR(30)
)

INSERT INTO Towns VALUES
('SILISTRA'),
('TARGOVISHTE'),
('VARNA'),
('BURGAS')

CREATE TABLE Addresses
(
 Id INT PRIMARY KEY IDENTITY(1,1),
 AddressText VARCHAR(50) NOT NULL,
 TownId INT NOT NULL
)

INSERT INTO Addresses VALUES
('UL.PURVA', 1),
('UL.VTORA',2),
('UL.TRETA',3),
('UL.CHETVARTA',4)

CREATE TABLE Departments
( 
 Id INT PRIMARY KEY IDENTITY(1,1),
 [Name] VARCHAR(30) NOT NULL
)

INSERT INTO Departments VALUES
('FRONT-END'),
('BACK-END'),
('FULL-STACK'),
('DESIGNER')

CREATE TABLE Employees
(
Id INT PRIMARY KEY IDENTITY(1,1),
FirstName VARCHAR(50) NOT NULL,
MiddleName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
JobTitle VARCHAR(50) NOT NULL,
DepartmentId INT NOT NULL,
HireDate DATETIME NOT NULL,
Salary DECIMAL(15,2) NOT NULL,
AddressId INT NOT NULL
)

INSERT INTO Employees VALUES
('YORDAN', 'MIROSLAVOV', 'VALKOV', 'JUNIOR',1, GETDATE(), 2400, 1),
('PETUR', 'PETROV', 'DIMITROV', 'INTERN',2, GETDATE(), 1200, 2),
('PLAMEN', 'ANDONOV', 'PETROV', 'SENIOR',3, GETDATE(), 4200, 3),
('GEORGI', 'PETROV', 'GEORGIEV', 'MID',4, GETDATE(), 3400, 4)

SELECT * FROM Towns
SELECT * FROM Departments
SELECT * FROM Employees

SELECT 
* FROM Towns
ORDER BY Name ASC

SELECT *
FROM Departments
ORDER BY Name ASC

SELECT * 
FROM Employees
ORDER BY Salary DESC

SELECT NAME FROM Towns
ORDER BY Name ASC

SELECT NAME FROM Departments
ORDER BY Name ASC

SELECT FirstName, LastName, JobTitle, Salary 
FROM Employees
ORDER BY Salary DESC

SELECT *FROM Employees

UPDATE Employees
SET Salary = Salary*1.10
SELECT Salary FROM Employees
